spring:
  application:
    name: CampusFormServer

  # 공통 JPA 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Google OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

server:
  forward-headers-strategy: framework
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    session:
      tracking-modes: cookie


# AWS S3
aws:
  s3:
    bucket: ${AWS_S3_BUCKET:dummy-bucket}
    region: ${AWS_S3_REGION:ap-northeast-2}
  credentials:
    access-key: ${AWS_ACCESS_KEY:dummy-access-key}
    secret-key: ${AWS_SECRET_KEY:dummy-secret-key}

# OAuth2 Redirect URI (공통 기본값)
app:
  oauth2:
    login-redirect-uri: ${FRONTEND_URL:http://localhost:3000}/auth/callback
    sheets-redirect-uri: ${FRONTEND_URL:http://localhost:3000}/oauth/google/callback
    allowed-redirect-uris: http://localhost:3000,https://web.campus-form-server.kro.kr

---
# 로컬 개발용
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

COOKIE_DOMAIN: ""
COOKIE_SECURE: false
COOKIE_SAME_SITE: lax

server:
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false

---
# 운영용
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  forward-headers-strategy: framework
  tomcat:
    internal-proxies: ".*"
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

  servlet:
    session:
      timeout: 24h
      cookie:
        domain: campus-form-server.kro.kr
        same-site: none
        secure: true
        http-only: true